# Quarto CLI completions, generated by quarto-completions.
# Quarto 99.9.9 (dev channel).
# Built from quarto-dev/quarto-cli main@2117a09798cba666b531b76642ee154e201b7d5c.
# Do not edit: https://github.com/mcanouil/quarto-completions

$script:QuartoCompletionSpec = @{
  '' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '-V' = 'Show the version number for this program.'
      '--version' = 'Show the version number for this program.'
    }
    Commands = @{
      'render' = 'Render files or projects to various document types.'
      'preview' = 'Render and preview a document or website project.'
      'serve' = 'Serve a Shiny interactive document.'
      'create' = 'Create a Quarto project or extension'
      'use' = 'Automate document or project setup tasks.'
      'add' = 'Add an extension to this folder or project'
      'update' = 'Updates an extension or global dependency (TinyTeX, Chromium (deprecated), Chrome Headless Shell, VeraPDF).'
      'remove' = 'Removes an extension.'
      'convert' = 'Convert documents to alternate representations.'
      'pandoc' = 'Run the version of Pandoc embedded within Quarto.'
      'typst' = 'Run the version of Typst embedded within Quarto.'
      'run' = 'Run a TypeScript, R, Python, or Lua script.'
      'list' = 'Lists an extension or global dependency.'
      'install' = 'Installs a global dependency (TinyTeX, Chromium (deprecated), Chrome Headless Shell, VeraPDF).'
      'uninstall' = 'Uninstalls a global dependency (TinyTeX, Chromium (deprecated), Chrome Headless Shell, VeraPDF).'
      'tools' = 'Display the status of Quarto installed dependencies'
      'publish' = 'Publish a document or project to a provider.'
      'check' = 'Verify correct functioning of Quarto installation.'
      'call' = 'Access functions of Quarto subsystems such as its rendering engines.'
      'capabilities' = 'Query for current capabilities (formats, engines, kernels etc.)'
      'inspect' = 'Inspect a Quarto project or input path.'
      'editor-support' = 'Miscellaneous tools to support Quarto editor modes'
      'create-project' = 'Create a project for rendering multiple documents'
      'completions' = 'Generate shell completions.'
      'dev-call' = 'Access internals of Quarto - this command is not intended for general use.'
    }
    Values = @{

    }
    Positional = @{

    }
    Variadic = $false
  }
  'render' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '-t' = 'Specify output format(s).'
      '--to' = 'Specify output format(s).'
      '-o' = 'Write output to FILE (use ''--output -'' for stdout).'
      '--output' = 'Write output to FILE (use ''--output -'' for stdout).'
      '--output-dir' = 'Write output to DIR (path is input/project relative)'
      '-M' = 'Metadata value (KEY:VALUE).'
      '--metadata' = 'Metadata value (KEY:VALUE).'
      '--site-url' = 'Override site-url for website or book output'
      '--execute' = 'Execute code (--no-execute to skip execution).'
      '-P' = 'Execution parameter (KEY:VALUE).'
      '--execute-param' = 'Execution parameter (KEY:VALUE).'
      '--execute-params' = 'YAML file with execution parameters.'
      '--execute-dir' = 'Working directory for code execution.'
      '--execute-daemon' = 'Keep Jupyter kernel alive (defaults to 300 seconds).'
      '--execute-daemon-restart' = 'Restart keepalive Jupyter kernel before render.'
      '--execute-debug' = 'Show debug output when executing computations.'
      '--use-freezer' = 'Force use of frozen computations for an incremental file render.'
      '--cache' = 'Cache execution output (--no-cache to prevent cache).'
      '--cache-refresh' = 'Force refresh of execution cache.'
      '--no-clean' = 'Do not clean project output-dir prior to render'
      '--debug' = 'Leave intermediate files in place after render.'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
      '--no-execute' = 'Negated form of --execute.'
      '--no-cache' = 'Negated form of --cache.'
      '--toc' = 'Include an automatically generated table of contents.'
      '--toc-depth' = 'Number of section levels in the table of contents.'
      '--number-sections' = 'Number section headings.'
      '--number-offset' = 'Offset for section headings.'
      '--top-level-division' = 'Treat top-level headings as this division.'
      '--standalone' = 'Produce a standalone document.'
      '--template' = 'Use FILE as a custom template.'
      '--css' = 'Link to a CSS style sheet.'
      '--bibliography' = 'Bibliography file.'
      '--csl' = 'Citation Style Language file.'
      '--citeproc' = 'Process citations with citeproc.'
      '--highlight-style' = 'Syntax highlighting style.'
      '--pdf-engine' = 'Engine used to produce PDF output.'
      '--mathjax' = 'Render mathematics with MathJax.'
      '--katex' = 'Render mathematics with KaTeX.'
      '--wrap' = 'Text wrapping in the output.'
      '--reference-doc' = 'Reference document for docx, pptx, or odt output.'
      '--shift-heading-level-by' = 'Shift heading levels by this amount.'
    }
    Commands = @{

    }
    Values = @{
      '-t' = @('html', 'pdf', 'docx', 'odt', 'rtf', 'revealjs', 'beamer', 'pptx', 'typst', 'dashboard', 'epub', 'gfm', 'commonmark', 'markdown', 'markua', 'hugo-md', 'docusaurus-md', 'jats', 'asciidoc', 'asciidoctor', 'ipynb', 'context', 'docbook', 'dokuwiki', 'jira', 'mediawiki', 'man', 'ms', 'muse', 'opml', 'org', 'rst', 'texinfo', 'textile', 'xwiki', 'zimwiki')
      '--to' = @('html', 'pdf', 'docx', 'odt', 'rtf', 'revealjs', 'beamer', 'pptx', 'typst', 'dashboard', 'epub', 'gfm', 'commonmark', 'markdown', 'markua', 'hugo-md', 'docusaurus-md', 'jats', 'asciidoc', 'asciidoctor', 'ipynb', 'context', 'docbook', 'dokuwiki', 'jira', 'mediawiki', 'man', 'ms', 'muse', 'opml', 'org', 'rst', 'texinfo', 'textile', 'xwiki', 'zimwiki')
      '-o' = @()
      '--output' = @()
      '--output-dir' = @()
      '-M' = @()
      '--metadata' = @()
      '--site-url' = @()
      '-P' = @()
      '--execute-param' = @()
      '--execute-params' = @()
      '--execute-dir' = @()
      '--execute-daemon' = @()
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
      '--toc-depth' = @()
      '--number-offset' = @()
      '--top-level-division' = @('default', 'section', 'chapter', 'part')
      '--template' = @()
      '--css' = @()
      '--bibliography' = @()
      '--csl' = @()
      '--highlight-style' = @()
      '--pdf-engine' = @('pdflatex', 'lualatex', 'xelatex', 'tectonic', 'latexmk', 'context', 'wkhtmltopdf', 'weasyprint', 'typst')
      '--wrap' = @('auto', 'none', 'preserve')
      '--reference-doc' = @()
      '--shift-heading-level-by' = @()
    }
    Positional = @{
      0 = @()
      1 = @()
      2 = @()
    }
    Variadic = $true
  }
  'preview' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--port' = 'Suggested port to listen on (defaults to random value between 3000 and 8000).'
      '--host' = 'Hostname to bind to (defaults to 127.0.0.1)'
      '--render' = 'Render to the specified format(s) before previewing (Default: "none")'
      '--no-serve' = 'Don''t run a local preview web server (just monitor and re-render input files)'
      '--no-navigate' = 'Don''t navigate the browser automatically when outputs are updated.'
      '--no-browser' = 'Don''t open a browser to preview the site.'
      '--no-watch-inputs' = 'Do not re-render input files when they change.'
      '--timeout' = 'Time (in seconds) after which to exit if there are no active clients.'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
      '--toc' = 'Include an automatically generated table of contents.'
      '--toc-depth' = 'Number of section levels in the table of contents.'
      '--number-sections' = 'Number section headings.'
      '--number-offset' = 'Offset for section headings.'
      '--top-level-division' = 'Treat top-level headings as this division.'
      '--standalone' = 'Produce a standalone document.'
      '--template' = 'Use FILE as a custom template.'
      '--css' = 'Link to a CSS style sheet.'
      '--bibliography' = 'Bibliography file.'
      '--csl' = 'Citation Style Language file.'
      '--citeproc' = 'Process citations with citeproc.'
      '--highlight-style' = 'Syntax highlighting style.'
      '--pdf-engine' = 'Engine used to produce PDF output.'
      '--mathjax' = 'Render mathematics with MathJax.'
      '--katex' = 'Render mathematics with KaTeX.'
      '--wrap' = 'Text wrapping in the output.'
      '--reference-doc' = 'Reference document for docx, pptx, or odt output.'
      '--shift-heading-level-by' = 'Shift heading levels by this amount.'
    }
    Commands = @{

    }
    Values = @{
      '--port' = @()
      '--host' = @()
      '--render' = @('all', 'html', 'pdf', 'docx', 'odt', 'rtf', 'revealjs', 'beamer', 'pptx', 'typst', 'dashboard', 'epub', 'gfm', 'commonmark', 'markdown', 'markua', 'hugo-md', 'docusaurus-md', 'jats', 'asciidoc', 'asciidoctor', 'ipynb', 'context', 'docbook', 'dokuwiki', 'jira', 'mediawiki', 'man', 'ms', 'muse', 'opml', 'org', 'rst', 'texinfo', 'textile', 'xwiki', 'zimwiki')
      '--timeout' = @()
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
      '--toc-depth' = @()
      '--number-offset' = @()
      '--top-level-division' = @('default', 'section', 'chapter', 'part')
      '--template' = @()
      '--css' = @()
      '--bibliography' = @()
      '--csl' = @()
      '--highlight-style' = @()
      '--pdf-engine' = @('pdflatex', 'lualatex', 'xelatex', 'tectonic', 'latexmk', 'context', 'wkhtmltopdf', 'weasyprint', 'typst')
      '--wrap' = @('auto', 'none', 'preserve')
      '--reference-doc' = @()
      '--shift-heading-level-by' = @()
    }
    Positional = @{
      0 = @()
      1 = @()
    }
    Variadic = $true
  }
  'serve' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--no-render' = 'Do not render the document before serving.'
      '-p' = 'The TCP port that the application should listen on.'
      '--port' = 'The TCP port that the application should listen on.'
      '--host' = 'Hostname to bind to (defaults to 127.0.0.1)'
      '--browser' = 'Open a browser to preview the site.'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '-p' = @()
      '--port' = @()
      '--host' = @()
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{
      0 = @()
    }
    Variadic = $false
  }
  'create' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--open' = 'Open new artifact in this editor (positron, vscode, rstudio)'
      '--no-open' = 'Do not open in an editor'
      '--no-prompt' = 'Do not prompt to confirm actions'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--open' = @('positron', 'vscode', 'rstudio')
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{
      0 = @('project', 'extension')
      1 = @()
    }
    Variadic = $true
  }
  'use' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--no-prompt' = 'Do not prompt to confirm actions'
    }
    Commands = @{
      'template' = 'Use a Quarto template for this directory or project.'
      'binder' = 'Configure the current project with Binder support.'
      'brand' = 'Use a brand for this project.'
    }
    Values = @{

    }
    Positional = @{
      0 = @()
      1 = @()
    }
    Variadic = $false
  }
  'use template' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--no-prompt' = 'Do not prompt to confirm actions'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
    }
    Commands = @{

    }
    Values = @{
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
    }
    Positional = @{
      0 = @()
    }
    Variadic = $false
  }
  'use binder' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--no-prompt' = 'Do not prompt to confirm actions'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
    }
    Commands = @{

    }
    Values = @{
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
    }
    Positional = @{

    }
    Variadic = $false
  }
  'use brand' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--force' = 'Skip all prompts and confirmations'
      '--dry-run' = 'Show what would happen without making changes'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{
      0 = @()
    }
    Variadic = $false
  }
  'add' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--no-prompt' = 'Do not prompt to confirm actions'
      '--embed' = 'Embed this extension within another extension (used when authoring extensions).'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--embed' = @()
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{
      0 = @()
    }
    Variadic = $false
  }
  'update' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--no-prompt' = 'Do not prompt to confirm actions'
      '--embed' = 'Embed this extension within another extension (used when authoring extensions).'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--embed' = @()
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{
      0 = @('tinytex', 'chrome-headless-shell', 'verapdf')
    }
    Variadic = $true
  }
  'remove' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--no-prompt' = 'Do not prompt to confirm actions'
      '--embed' = 'Remove this extension from within another extension (used when authoring extensions).'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--embed' = @()
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{
      0 = @()
    }
    Variadic = $true
  }
  'convert' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '-o' = 'Write output to PATH.'
      '--output' = 'Write output to PATH.'
      '--with-ids' = 'Include ids in conversion'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '-o' = @()
      '--output' = @()
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{
      0 = @()
    }
    Variadic = $false
  }
  'pandoc' = @{
    Options = @{

    }
    Commands = @{

    }
    Values = @{

    }
    Positional = @{

    }
    Variadic = $false
  }
  'typst' = @{
    Options = @{

    }
    Commands = @{

    }
    Values = @{

    }
    Positional = @{

    }
    Variadic = $false
  }
  'run' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{
      0 = @()
      1 = @()
    }
    Variadic = $true
  }
  'list' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{
      0 = @('extensions', 'tools')
    }
    Variadic = $false
  }
  'install' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--no-prompt' = 'Do not prompt to confirm actions'
      '--update-path' = 'Update system path when a tool is installed'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{
      0 = @('tinytex', 'chrome-headless-shell', 'verapdf')
    }
    Variadic = $true
  }
  'uninstall' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--no-prompt' = 'Do not prompt to confirm actions'
      '--update-path' = 'Update system path when a tool is installed'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{
      0 = @('tinytex', 'chrome-headless-shell', 'verapdf')
    }
    Variadic = $false
  }
  'tools' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
    }
    Commands = @{
      'install' = 'Installs a global dependency.'
      'info' = 'Shows the status of a global dependency.'
      'uninstall' = 'Uninstalls a global dependency.'
      'update' = 'Updates a global dependency.'
      'list' = 'Lists the status of every global dependency.'
    }
    Values = @{

    }
    Positional = @{

    }
    Variadic = $false
  }
  'tools install' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
    }
    Commands = @{

    }
    Values = @{

    }
    Positional = @{
      0 = @('tinytex', 'chrome-headless-shell', 'verapdf')
    }
    Variadic = $false
  }
  'tools info' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
    }
    Commands = @{

    }
    Values = @{

    }
    Positional = @{
      0 = @('tinytex', 'chrome-headless-shell', 'verapdf')
    }
    Variadic = $false
  }
  'tools uninstall' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
    }
    Commands = @{

    }
    Values = @{

    }
    Positional = @{
      0 = @('tinytex', 'chrome-headless-shell', 'verapdf')
    }
    Variadic = $false
  }
  'tools update' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
    }
    Commands = @{

    }
    Values = @{

    }
    Positional = @{
      0 = @('tinytex', 'chrome-headless-shell', 'verapdf')
    }
    Variadic = $false
  }
  'tools list' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{

    }
    Variadic = $false
  }
  'publish' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--id' = 'Identifier of content to publish'
      '--server' = 'Server to publish to'
      '--token' = 'Access token for publising provider'
      '--no-render' = 'Do not render before publishing.'
      '--no-prompt' = 'Do not prompt to confirm publishing destination'
      '--no-browser' = 'Do not open a browser to the site after publishing'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--id' = @()
      '--server' = @()
      '--token' = @()
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{
      0 = @('quarto-pub', 'gh-pages', 'connect', 'posit-connect-cloud', 'netlify', 'confluence', 'huggingface')
      1 = @()
    }
    Variadic = $false
  }
  'check' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--output' = 'Output as JSON to a file'
      '--no-strict' = 'When set, will not fail if dependency versions don''t match precisely'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--output' = @()
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{
      0 = @('install', 'jupyter', 'knitr', 'versions', 'all')
    }
    Variadic = $false
  }
  'call' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
    }
    Commands = @{
      'engine' = 'Access functionality specific to quarto''s different rendering engines.'
      'build-ts-extension' = 'Build TypeScript execution engine extensions.'
      'typst-gather' = 'Gather Typst packages for a format extension.'
    }
    Values = @{

    }
    Positional = @{

    }
    Variadic = $false
  }
  'call engine' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
    }
    Commands = @{

    }
    Values = @{
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
    }
    Positional = @{
      0 = @('jupyter', 'knitr', 'markdown', 'julia')
      1 = @()
    }
    Variadic = $true
  }
  'call build-ts-extension' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--check' = 'Type-check only (skip bundling)'
      '--init-config' = 'Generate deno.json with absolute importMap path'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
    }
    Commands = @{

    }
    Values = @{
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
    }
    Positional = @{
      0 = @()
    }
    Variadic = $false
  }
  'call typst-gather' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--init-config' = 'Generate a starter typst-gather.toml in current directory'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{

    }
    Variadic = $false
  }
  'capabilities' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{

    }
    Variadic = $false
  }
  'inspect' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{
      0 = @()
      1 = @()
    }
    Variadic = $false
  }
  'editor-support' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
    }
    Commands = @{
      'crossref' = 'Index cross references for content'
    }
    Values = @{

    }
    Positional = @{

    }
    Variadic = $false
  }
  'editor-support crossref' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '-i' = 'Use FILE as input (default: stdin).'
      '--input' = 'Use FILE as input (default: stdin).'
      '-o' = 'Write output to FILE (default: stdout).'
      '--output' = 'Write output to FILE (default: stdout).'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{
      0 = @()
    }
    Variadic = $true
  }
  'create-project' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--title' = 'Project title'
      '--type' = 'Project type (book, default, website, manuscript)'
      '--template' = 'Use a specific project template'
      '--engine' = 'Use execution engine (jupyter, knitr, markdown, ...)'
      '--editor' = 'Default editor for project (''source'' or ''visual'')'
      '--with-venv' = 'Create a virtualenv for this project'
      '--with-condaenv' = 'Create a condaenv for this project'
      '--no-scaffold' = 'Don''t create initial project file(s)'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--title' = @()
      '--type' = @('book', 'default', 'website', 'manuscript')
      '--template' = @()
      '--engine' = @('jupyter', 'knitr', 'markdown', 'julia')
      '--editor' = @('source', 'visual')
      '--with-venv' = @()
      '--with-condaenv' = @()
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
      '--profile' = @()
    }
    Positional = @{
      0 = @()
    }
    Variadic = $false
  }
  'completions' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
    }
    Commands = @{
      'bash' = 'Generate shell completions for bash.'
      'fish' = 'Generate shell completions for fish.'
      'zsh' = 'Generate shell completions for zsh.'
    }
    Values = @{

    }
    Positional = @{

    }
    Variadic = $false
  }
  'completions bash' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '-n' = 'The name of the main command.'
      '--name' = 'The name of the main command.'
    }
    Commands = @{

    }
    Values = @{
      '-n' = @()
      '--name' = @()
    }
    Positional = @{

    }
    Variadic = $false
  }
  'completions fish' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '-n' = 'The name of the main command.'
      '--name' = 'The name of the main command.'
    }
    Commands = @{

    }
    Values = @{
      '-n' = @()
      '--name' = @()
    }
    Positional = @{

    }
    Variadic = $false
  }
  'completions zsh' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '-n' = 'The name of the main command. (Default: "quarto")'
      '--name' = 'The name of the main command. (Default: "quarto")'
    }
    Commands = @{

    }
    Values = @{
      '-n' = @()
      '--name' = @()
    }
    Positional = @{

    }
    Variadic = $false
  }
  'dev-call' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
    }
    Commands = @{
      'cli-info' = 'Generate JSON information about the Quarto CLI.'
      'validate-yaml' = 'Validates a YAML file against Quarto''s schemas.'
      'build-artifacts' = 'Builds all the javascript assets necessary for IDE support.'
      'show-ast-trace' = 'Renders the document with AST tracing enabled and then shows the debugging output.'
      'make-ast-diagram' = 'Creates a diagram of the Pandoc AST.'
      'pull-git-subtree' = 'Pull configured git subtrees.'
      'typst-gather' = 'Gather Typst packages for offline/hermetic builds.'
    }
    Values = @{

    }
    Positional = @{

    }
    Variadic = $false
  }
  'dev-call cli-info' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--log' = 'Path to log file'
      '--log-level' = 'Log level (debug, info, warning, error, critical)'
      '--log-format' = 'Log format (plain, json-stream)'
      '--quiet' = 'Suppress console output.'
    }
    Commands = @{

    }
    Values = @{
      '--log' = @()
      '--log-level' = @('debug', 'info', 'warning', 'error', 'critical')
      '--log-format' = @('plain', 'json-stream')
    }
    Positional = @{

    }
    Variadic = $false
  }
  'dev-call validate-yaml' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '-s' = 'Name of schema in Quarto''s definitions.yml. If string ends with .yml, it is treated as a file name for a new schema, which is validated, loaded, and then used.'
      '--schema' = 'Name of schema in Quarto''s definitions.yml. If string ends with .yml, it is treated as a file name for a new schema, which is validated, loaded, and then used.'
      '--json' = 'If set, output error messages in JSON format.'
    }
    Commands = @{

    }
    Values = @{
      '-s' = @()
      '--schema' = @()
    }
    Positional = @{
      0 = @()
    }
    Variadic = $false
  }
  'dev-call build-artifacts' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
    }
    Commands = @{

    }
    Values = @{

    }
    Positional = @{

    }
    Variadic = $false
  }
  'dev-call show-ast-trace' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
    }
    Commands = @{

    }
    Values = @{

    }
    Positional = @{
      0 = @()
    }
    Variadic = $true
  }
  'dev-call make-ast-diagram' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '-m' = 'Diagram mode (default: full)'
      '--mode' = 'Diagram mode (default: full)'
    }
    Commands = @{

    }
    Values = @{
      '-m' = @()
      '--mode' = @()
    }
    Positional = @{
      0 = @()
    }
    Variadic = $true
  }
  'dev-call pull-git-subtree' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
    }
    Commands = @{

    }
    Values = @{

    }
    Positional = @{
      0 = @('all', 'julia-engine', 'orange-book')
    }
    Variadic = $false
  }
  'dev-call typst-gather' = @{
    Options = @{
      '-h' = 'Show this help.'
      '--help' = 'Show this help.'
      '--profile' = 'Active project profile(s)'
    }
    Commands = @{

    }
    Values = @{
      '--profile' = @()
    }
    Positional = @{

    }
    Variadic = $false
  }
}

# Walks the words typed so far, resolving the command path and how many
# positionals follow it. Words consumed as flag values are not positionals.
function Script:Resolve-QuartoNode {
  param([string[]]$Words)

  $path = @()
  $position = 0
  $skip = $false
  # Values is keyed by every flag that consumes the next word, so its key set
  # doubles as the valued-flag list.
  $valued = $script:QuartoCompletionSpec[''].Values

  foreach ($word in $Words) {
    if ($skip) { $skip = $false; continue }
    if ($word.StartsWith('-')) {
      if ($valued.ContainsKey($word)) { $skip = $true }
      continue
    }
    $candidate = (($path + $word) -join ' ')
    if ($script:QuartoCompletionSpec.ContainsKey($candidate)) {
      $path += $word
      $position = 0
      $valued = $script:QuartoCompletionSpec[$candidate].Values
      continue
    }
    $position++
  }

  return [pscustomobject]@{
    Node     = $script:QuartoCompletionSpec[($path -join ' ')]
    Position = $position
  }
}

function Script:New-QuartoResult {
  param([string]$Text, [string]$Tooltip)

  [System.Management.Automation.CompletionResult]::new(
    $Text,
    $Text,
    'ParameterValue',
    $(if ([string]::IsNullOrWhiteSpace($Tooltip)) { $Text } else { $Tooltip })
  )
}

$script:QuartoCompleter = {
  param($wordToComplete, $commandAst, $cursorPosition)

  $words = @($commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { $_.ToString() })
  # Drop the partial word the user is typing. A range ending at -1 would wrap
  # around and repeat the whole array, so the single-word case is explicit.
  if ($words.Count -gt 0 -and $words[-1] -eq $wordToComplete) {
    if ($words.Count -gt 1) {
      $words = @($words[0..($words.Count - 2)])
    }
    else {
      $words = @()
    }
  }

  $resolved = Script:Resolve-QuartoNode -Words $words
  $node = $resolved.Node
  if ($null -eq $node) { return }

  # A flag expecting a value wins over commands and positionals.
  $previous = if ($words.Count -gt 0) { $words[-1] } else { '' }
  if ($node.Values.ContainsKey($previous)) {
    return $node.Values[$previous] |
      Where-Object { $_ -like "$wordToComplete*" } |
      ForEach-Object { Script:New-QuartoResult -Text $_ }
  }

  if ($wordToComplete.StartsWith('-')) {
    return $node.Options.GetEnumerator() |
      Where-Object { $_.Key -like "$wordToComplete*" } |
      Sort-Object Key |
      ForEach-Object { Script:New-QuartoResult -Text $_.Key -Tooltip $_.Value }
  }

  $results = @()
  if ($resolved.Position -eq 0) {
    $results += $node.Commands.GetEnumerator() |
      Where-Object { $_.Key -like "$wordToComplete*" } |
      Sort-Object Key |
      ForEach-Object { Script:New-QuartoResult -Text $_.Key -Tooltip $_.Value }
  }

  $slot = $resolved.Position
  if ($node.Variadic -and $slot -ge $node.Positional.Count) {
    $slot = $node.Positional.Count - 1
  }
  if ($slot -ge 0 -and $slot -lt $node.Positional.Count) {
    $results += $node.Positional[$slot] |
      Where-Object { $_ -like "$wordToComplete*" } |
      ForEach-Object { Script:New-QuartoResult -Text $_ }
  }
  return $results
}

Register-ArgumentCompleter -Native -CommandName quarto -ScriptBlock $script:QuartoCompleter
Register-ArgumentCompleter -Native -CommandName quarto.cmd -ScriptBlock $script:QuartoCompleter
