/**
 * Helpers shared by the four emitters.
 */

import type { ArgSpec, CommandSpec, OptionSpec, Spec } from "../spec.ts";
import { walk } from "../spec.ts";

/** Header every generated script carries, so its provenance is on the file. */
export function banner(spec: Spec, comment: string): string {
  return [
    `${comment} Quarto CLI completions, generated by quarto-completions.`,
    `${comment} Quarto ${spec.quartoVersion} (${spec.channel} channel), generated ${spec.generated}.`,
    `${comment} Do not edit: https://github.com/mcanouil/quarto-completions`,
  ].join("\n");
}

/** Every command in the tree, root first. */
export function nodes(spec: Spec): CommandSpec[] {
  return walk(spec.root);
}

/** All flag spellings of a command, in declaration order. */
export function flags(command: CommandSpec): string[] {
  return command.options.flatMap((option) =>
    [option.short, option.long].filter((flag): flag is string => !!flag)
  );
}

/**
 * Positionals in the order they are typed. A variadic argument keeps applying
 * once reached, which is how `quarto install tinytex verapdf` completes its
 * second tool.
 */
export function positionals(command: CommandSpec): ArgSpec[] {
  return command.args.filter((arg) => arg.kind !== "value" || arg.values);
}

/** Whether the last positional keeps applying to every further word. */
export function trailingIsVariadic(command: CommandSpec): boolean {
  const args = positionals(command);
  return args.length > 0 && args[args.length - 1].variadic;
}

/** Options that consume the next word. */
export function valuedOptions(command: CommandSpec): OptionSpec[] {
  return command.options.filter((option) => option.kind !== "none");
}

/** Escapes a description for a single-quoted shell string. */
export function singleQuote(text: string): string {
  return text.replace(/'/g, "'\\''");
}

/** Collapses a description to one line, since every shell shows it as one. */
export function oneLine(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}
