/**
 * Helpers shared by the four emitters.
 */

import type { ArgSpec, CommandSpec, OptionSpec, Spec } from "../spec.ts";
import { optionFlags, walk } from "../spec.ts";

/** Where every completed surface is read out of. */
const kQuartoRepository = "quarto-dev/quarto-cli";

/**
 * Header every generated script carries, so its provenance is on the file.
 *
 * Deliberately no generation date: it would change on every run and make each
 * script differ from the committed one even when the CLI surface had not
 * moved. The date belongs in `manifest.json`, which is expected to churn.
 *
 * The commit a `dev` script was built from is here on purpose, and it does
 * churn: a source build reports 99.9.9 and names no tag, so this line is the
 * only thing on an installed dev completion that says which surface it came
 * from. The price is that the weekly regeneration sees a byte change whenever
 * quarto-cli's main has moved, rather than only when the CLI surface has.
 *
 * The version line above it is parsed by `docs/install.sh`, which is why the
 * source goes on a line of its own rather than onto the end of that one.
 */
export function banner(spec: Spec, comment: string): string {
  const source = sourceLine(spec);
  return [
    `${comment} Quarto CLI completions, generated by quarto-completions.`,
    `${comment} Quarto ${spec.quartoVersion} (${spec.channel} channel).`,
    ...(source ? [`${comment} Built from ${kQuartoRepository} ${source}.`] : []),
    `${comment} Do not edit: https://github.com/mcanouil/quarto-completions`,
  ].join("\n");
}

/** The artefact a spec names, e.g. `v1.10.18` or `main@e3f1c0ab…`; empty when it names none. */
function sourceLine(spec: Spec): string {
  const source = spec.source;
  if (source === undefined) {
    return "";
  }
  if (source.tag !== undefined) {
    return source.tag;
  }
  if (source.commit === undefined) {
    return source.branch ?? "";
  }
  return source.branch === undefined ? source.commit : `${source.branch}@${source.commit}`;
}

/** Every command in the tree, root first. */
export function nodes(spec: Spec): CommandSpec[] {
  return walk(spec.root);
}

/** All flag spellings of a command, in declaration order. */
export function flags(command: CommandSpec): string[] {
  return command.options.flatMap(optionFlags);
}

/** Flags of a command that consume the word after them. */
export function valuedFlags(command: CommandSpec): string[] {
  return valuedOptions(command).flatMap(optionFlags);
}

/**
 * Positionals in the order they are typed, all of them.
 *
 * The index into this list is the slot number every emitter dispatches on, and
 * the generated scripts count every non-flag word. Dropping the positionals
 * with nothing to suggest would renumber the rest and misalign the two.
 */
export function positionals(command: CommandSpec): ArgSpec[] {
  return command.args;
}

/** Whether the last positional keeps applying to every further word. */
export function trailingIsVariadic(command: CommandSpec): boolean {
  const args = positionals(command);
  return args.length > 0 && args[args.length - 1].variadic;
}

/** Options that consume the next word. */
export function valuedOptions(command: CommandSpec): OptionSpec[] {
  return command.options.filter((option) => option.kind !== "none");
}

/** Escapes a description for a single-quoted shell string. */
export function singleQuote(text: string): string {
  return text.replace(/'/g, "'\\''");
}

/** Collapses a description to one line, since every shell shows it as one. */
export function oneLine(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}
